### ISSUE TITLE
leave razor code on local filesystem

### ISSUE THREAD

**Issue by bodepd** [stephenrjohnson/razor-puppet-puppetdb-demo#4]
Hi Stephen,

I was thinking about how your tool could be used to build a development environment for razor itself.

This would require that razor stay on the local filesystem and be mounted into the master node.

This may be moving too far away from your original use case.

what do you think?

**Comment by stephenrjohnson** [comment]
Good plan we simply need to arrange a vagrant exported filesystem. We
could easily do this and it would be a useful addition. Just need to thing of a nice
way to add this as an options or maybe s branch

**Comment by stephenrjohnson** [comment]
I have looked at the vagrant docs and it doesn't seem like you can specify a Vagrantfile, as i was planning to wrap vagrant up/down etc in a rake task and have. 

rake up[puppetdemo]
rake up[razordev]
rake down[puppetdemo]
rake down[razordev]

Then just change the vagrant config for each environment and refactor the puppet manifest to handel this. Although strangely it seems like you cant do it, unless i have missed something.

**Comment by stephenrjohnson** [comment]
I have created the idea of environments and used tags for this to work. Simple create a new evn/razor-dev for example.
